workflows:
  react-native-android:
    name: Build React Native Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.yourcompany.yourapp"
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android App Bundle
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - "your-email@example.com"

