workflows:
  react-native-android:
    name: Build React Native Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.digiconapp"  # Replace this with your actual package name
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          echo "Checking Node.js & NPM versions..."
          node -v
          npm -v
          
          echo "Installing dependencies..."
          npm install
          npx pod-install

      - name: Prepare Android Build
        script: |
          echo "Setting up Java & Watchman..."
          brew install watchman
          java -version

          echo "Cleaning Gradle cache..."
          cd android
          ./gradlew clean
          chmod +x gradlew

      - name: Build Android App Bundle
        script: |
          echo "Building AAB file..."
          cd android
          ./gradlew bundleRelease || { echo "Build failed!" && exit 1; }

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - "misbahsshanidia@gmail.com"  # Change this to your actual email

