# Generated by Django 5.1.6 on 2025-03-03 19:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_bio_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=50)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to=api.models.upload_to)),
            ],
        ),
    ]
