# Generated by Django 5.1.6 on 2025-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_container_image_delete_containerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='container_images/%Y/%m/%d/'),
        ),
    ]
